# Generated by Django 5.1.5 on 2025-02-25 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sid', models.CharField(max_length=36, unique=True)),
                ('trademark', models.CharField(blank=True, max_length=255, null=True)),
                ('api_token', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location_id', models.IntegerField(unique=True, verbose_name='ID локации')),
                ('office_id', models.IntegerField(verbose_name='ID офиса')),
                ('cargo_type', models.IntegerField(verbose_name='Тип груза')),
                ('delivery_type', models.IntegerField(verbose_name='Тип доставки')),
            ],
        ),
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
                ('sellerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='sellersinfo.sellers', to_field='sid')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField()),
                ('imtid', models.IntegerField(blank=True, null=True)),
                ('nmuuid', models.CharField(blank=True, max_length=36, null=True)),
                ('subjectid', models.IntegerField(blank=True, null=True)),
                ('subjectname', models.CharField(blank=True, max_length=255, null=True)),
                ('vendorcode', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('needkiz', models.BooleanField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellersinfo.sellers', to_field='sid')),
            ],
        ),
    ]
