# Generated by Django 5.1.5 on 2025-03-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellersinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sellersinfo.sellers', verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='StorageCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_code', models.CharField(max_length=50, verbose_name='Код ячейки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание ячейки')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sellersinfo.warehouse', verbose_name='Склад')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара в ячейке')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='sellersinfo.cards', verbose_name='Товар')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='sellersinfo.storagecell', verbose_name='Ячейка')),
            ],
        ),
    ]
