# Generated by Django 5.1.5 on 2025-03-23 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellersinfo', '0002_warehouse_owner_storagecell_productplacement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sellersinfo.sellers', verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес склада')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to=settings.AUTH_USER_MODEL, verbose_name='Склад')),
            ],
        ),
        migrations.AlterField(
            model_name='storagecell',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sellersinfo.storage', verbose_name='Склад'),
        ),
    ]
